<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261005184830 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Колоды: базовые (без владельца, из контента) и колоды игроков; состав — deck_cards';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE deck_cards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity SMALLINT NOT NULL, deck_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C59FA212111948DC ON deck_cards (deck_id)');
        $this->addSql('CREATE INDEX IDX_C59FA2124ACC9A20 ON deck_cards (card_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_deck_cards_deck_card ON deck_cards (deck_id, card_id)');
        $this->addSql('CREATE TABLE decks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3FCC6327E3C61F9 ON decks (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_decks_slug ON decks (slug)');
        $this->addSql('ALTER TABLE deck_cards ADD CONSTRAINT FK_C59FA212111948DC FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deck_cards ADD CONSTRAINT FK_C59FA2124ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE decks ADD CONSTRAINT FK_A3FCC6327E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE deck_cards DROP CONSTRAINT FK_C59FA212111948DC');
        $this->addSql('ALTER TABLE deck_cards DROP CONSTRAINT FK_C59FA2124ACC9A20');
        $this->addSql('ALTER TABLE decks DROP CONSTRAINT FK_A3FCC6327E3C61F9');
        $this->addSql('DROP TABLE deck_cards');
        $this->addSql('DROP TABLE decks');
    }
}
