<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260803181152 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE abilities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(50) DEFAULT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE card_abilities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value INT DEFAULT NULL, card_id INT NOT NULL, ability_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC306EF04ACC9A20 ON card_abilities (card_id)');
        $this->addSql('CREATE INDEX IDX_CC306EF08016D8B2 ON card_abilities (ability_id)');
        $this->addSql('CREATE TABLE card_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, icon VARCHAR(50) DEFAULT NULL, slug VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, mana_cost INT NOT NULL, attack INT DEFAULT NULL, health INT DEFAULT NULL, image_path VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, race_id INT NOT NULL, card_type_id INT NOT NULL, rarity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cards_race ON cards (race_id)');
        $this->addSql('CREATE INDEX idx_cards_type ON cards (card_type_id)');
        $this->addSql('CREATE INDEX idx_cards_rarity ON cards (rarity_id)');
        $this->addSql('CREATE INDEX idx_cards_race_type ON cards (race_id, card_type_id)');
        $this->addSql('CREATE INDEX idx_cards_mana_type ON cards (mana_cost, card_type_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cards_name ON cards (name)');
        $this->addSql('CREATE TABLE card_tags (card_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (card_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_838F96844ACC9A20 ON card_tags (card_id)');
        $this->addSql('CREATE INDEX IDX_838F9684BAD26311 ON card_tags (tag_id)');
        $this->addSql('CREATE TABLE races (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, slug VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rarities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, color_hex VARCHAR(7) NOT NULL, drop_chance INT NOT NULL, slug VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(50) DEFAULT NULL, color_hex VARCHAR(7) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE card_abilities ADD CONSTRAINT FK_CC306EF04ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_abilities ADD CONSTRAINT FK_CC306EF08016D8B2 FOREIGN KEY (ability_id) REFERENCES abilities (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_4C258FD6E59D40D FOREIGN KEY (race_id) REFERENCES races (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_4C258FD925606E5 FOREIGN KEY (card_type_id) REFERENCES card_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_4C258FDF3747573 FOREIGN KEY (rarity_id) REFERENCES rarities (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_tags ADD CONSTRAINT FK_838F96844ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_tags ADD CONSTRAINT FK_838F9684BAD26311 FOREIGN KEY (tag_id) REFERENCES tags (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE card_abilities DROP CONSTRAINT FK_CC306EF04ACC9A20');
        $this->addSql('ALTER TABLE card_abilities DROP CONSTRAINT FK_CC306EF08016D8B2');
        $this->addSql('ALTER TABLE cards DROP CONSTRAINT FK_4C258FD6E59D40D');
        $this->addSql('ALTER TABLE cards DROP CONSTRAINT FK_4C258FD925606E5');
        $this->addSql('ALTER TABLE cards DROP CONSTRAINT FK_4C258FDF3747573');
        $this->addSql('ALTER TABLE card_tags DROP CONSTRAINT FK_838F96844ACC9A20');
        $this->addSql('ALTER TABLE card_tags DROP CONSTRAINT FK_838F9684BAD26311');
        $this->addSql('DROP TABLE abilities');
        $this->addSql('DROP TABLE card_abilities');
        $this->addSql('DROP TABLE card_types');
        $this->addSql('DROP TABLE cards');
        $this->addSql('DROP TABLE card_tags');
        $this->addSql('DROP TABLE races');
        $this->addSql('DROP TABLE rarities');
        $this->addSql('DROP TABLE tags');
    }
}
