<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261005190032 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Партии: игроки, статус, состояние движка (JSON), версия для оптимистичной блокировки';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE games (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, seed INT DEFAULT NULL, state JSON DEFAULT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, player0_id INT NOT NULL, player1_id INT DEFAULT NULL, creator_deck_id INT DEFAULT NULL, winner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF232B3178256346 ON games (player0_id)');
        $this->addSql('CREATE INDEX IDX_FF232B31C0990423 ON games (player1_id)');
        $this->addSql('CREATE INDEX IDX_FF232B319F8BF1A8 ON games (creator_deck_id)');
        $this->addSql('CREATE INDEX IDX_FF232B315DFCD4B8 ON games (winner_id)');
        $this->addSql('CREATE INDEX idx_games_status ON games (status)');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT FK_FF232B3178256346 FOREIGN KEY (player0_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT FK_FF232B31C0990423 FOREIGN KEY (player1_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT FK_FF232B319F8BF1A8 FOREIGN KEY (creator_deck_id) REFERENCES decks (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE games ADD CONSTRAINT FK_FF232B315DFCD4B8 FOREIGN KEY (winner_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE games DROP CONSTRAINT FK_FF232B3178256346');
        $this->addSql('ALTER TABLE games DROP CONSTRAINT FK_FF232B31C0990423');
        $this->addSql('ALTER TABLE games DROP CONSTRAINT FK_FF232B319F8BF1A8');
        $this->addSql('ALTER TABLE games DROP CONSTRAINT FK_FF232B315DFCD4B8');
        $this->addSql('DROP TABLE games');
    }
}
