<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006061721 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ходы партии: кто ходил и события — журнал партии после перезагрузки страницы';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE game_moves (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor SMALLINT DEFAULT NULL, events JSON NOT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_game_moves_game ON game_moves (game_id)');
        $this->addSql('ALTER TABLE game_moves ADD CONSTRAINT FK_770C71BDE48FD905 FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE game_moves DROP CONSTRAINT FK_770C71BDE48FD905');
        $this->addSql('DROP TABLE game_moves');
    }
}
